# Generated by Django 5.0.6 on 2024-06-19 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flower',
            options={'verbose_name': 'Flower', 'verbose_name_plural': 'Flowers'},
        ),
    ]
