# Generated by Django 5.0.6 on 2024-06-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_flower_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
